name: Check in

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

  # UTC时间，对应Beijing时间 8：30
  #schedule:
  #  - cron: "33 00 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: enwaiax/smzdm_bot
      env:
        ANDROID_COOKIE: ${{ secrets.ANDROID_COOKIE }}
        SK: ${{ secrets.SK }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        SC_KEY: ${{ secrets.SC_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_BOT_API: ${{ secrets.TG_BOT_API }}
    steps:
      - name: Working
        run: |
          echo "ANDROID_COOKIE: ${{ secrets.ANDROID_COOKIE }}"
          echo "SK: ${{ secrets.SK }}"
          echo "PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}"
          echo "SC_KEY: ${{ secrets.SC_KEY }}"
          echo "TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}"
          echo "TG_USER_ID: ${{ secrets.TG_USER_ID }}"
          echo "TG_BOT_API: ${{ secrets.TG_BOT_API }}"
          python /smzdm_bot/main.py
